### PR TITLE
Added support for Python 3

### PR DESCRIPTION
**Pull request by jneves**
Using six for compatibility between Python 2 and Python 3 in the same codebase.

### CODE REVIEW

**Comment by martinogden** [comment]
Nice, I hadn't thought about Python 3 support. However, Django [recommends](https://docs.djangoproject.com/en/dev/topics/python3/#unicode-literals) using `from __future__ import unicode_literals` to deal with unicode for in versions 2.\* and 3.\* and I'd like to stick with their guidelines here. Is there any benefit to using six rather than unicode_literals?

**Comment by jneves** [comment]
You're right, I'll reimplement the changes tomorrow that way. Not sure how that works with the admin.py patch for force_unicode, but I'll test it.

**Comment by jneves** [comment]
Done :).

**Comment by martinogden** [comment]
Thanks!

**Pull request merged**
